#!/bin/tcsh -f
#
## solve individual GO problems using Knitro.
##
## Orig:  R. Waltz 2019
#

\rm score*.txt
\rm solution_*.txt
\rm solution2_*.txt
\rm eval_*.json
\rm *eval.log
\rm saved_solution*.bin
\rm base*.txt
\rm write_ctgs.log
\rm heur1.txt
\rm heur1.bin
\rm priorbase.txt

# Set main Problem repository
set DIR = /Users/rwaltz/go/go2mom/networks

# Set problem name

#set OUTDIR = /Users/rwaltz/go/output/ODReal1/net01
#set OUTDIR = ${DIR}/

# Set working directory

set SOLVES = $PWD

# Get the list of problems

#set list = `ls -F ${DIR}`
#set list = $<
set list = `more testList`

# Now solve

foreach network ( $list )
#while ( "$list" != '' )

# Create directory if necessary
#    set network = $list
    echo ${network}
    #if( ! -d ${OUTDIR}/${network} ) mkdir ${OUTDIR}/${network}

# Solve current problem ; keep output on the screen and redirect to a file
# At the same time, update the summary file.
    #cd ${network}
    echo "......solving ${network}" | tee ${network}.knitro

    #python3 MyPython1.py case.con case.json case.raw 0 600 1 'test'
    #python3 MyPython2.py case.con case.json case.raw 0 600 1 'test'
    python3 MyPython1.py ${DIR}/${network}/case.con ${DIR}/${network}/case.json ${DIR}/${network}/case.raw 0 1000 4 'test'
    #python3 MyPython2.py ${DIR}/${network}/case.con ${DIR}/${network}/case.json ${DIR}/${network}/case.raw 0  10000 4 'test'

    #\cp knitro.log ${OUTDIR}/${network}/
    #\cp ${network}.knitro ${OUTDIR}/${network}/
    #\cp knitro.log ${OUTDIR}/${network}/${network}.log
    #\cp kdbg*.log ${OUTDIR}/${network}/

    #cd ..

#    set list = $<

end

exit 0
